INSERT INTO `AuthItem` (`name`, `type`, `description`, `bizrule`, `data`) VALUES
('addSiteNewLanguage', 0, '', NULL, 'N;'),
('changeMail', 0, '', NULL, 'N;'),
('contact', 0, '', NULL, 'N;'),
('createContent', 0, '', NULL, 'N;'),
('createNews', 0, '', NULL, 'N;'),
('createSite', 0, '', NULL, 'N;'),
('deleteContent', 0, '', NULL, 'N;'),
('deleteNews', 0, '', NULL, 'N;'),
('deleteSite', 0, '', NULL, 'N;'),
('deleteSiteLanguage', 0, '', NULL, 'N;'),
('editNews', 0, '', NULL, 'N;'),
('editSite', 0, '', NULL, 'N;'),
('editContent', 0, '', NULL, 'N;');
('login', 0, '', NULL, 'N;'),
('logout', 0, '', NULL, 'N;'),
('MEMBER', 2, '', NULL, 'N;'),
('MNEWS', 2, '', NULL, 'N;'),
('MSITE', 2, '', NULL, 'N;'),
('register', 0, '', NULL, 'N;'),
('resendMail', 0, '', NULL, 'N;'),
('updateContent', 0, '', NULL, 'N;'),
('updateNews', 0, '', NULL, 'N;'),
('updateSite', 0, '', NULL, 'N;'),
('USER', 2, '', NULL, 'N;'),
('VISITOR', 2, '', NULL, 'N;'),
('deleteGallery', 0, '', NULL, 'N;'),
('editGallery', 0, '', NULL, 'N;'),
('MGALLERY', 2, '', NULL, 'N;'),
('updateGallery', 0, '', NULL, 'N;'),
('addSiteContent', 0, '', NULL, 'N;'),
('deleteSiteContent', 0, '', NULL, 'N;'),
('updateContentText', 0, '', NULL, 'N;');

INSERT INTO `AuthItemChild` (`parent`, `child`) VALUES
('MSITE', 'addSiteNewLanguage'),
('VISITOR', 'changeMail'),
('USER', 'contact'),
('VISITOR', 'contact'),
('MSITE', 'createContent'),
('MNEWS', 'createNews'),
('MSITE', 'createSite'),
('MSITE', 'deleteContent'),
('MNEWS', 'deleteNews'),
('MSITE', 'deleteSite'),
('MSITE', 'deleteSiteLanguage'),
('MNEWS', 'editNews'),
('MSITE', 'editSite'),
('MSITE', 'editContent'),
('VISITOR', 'login'),
('USER', 'logout'),
('VISITOR', 'register'),
('VISITOR', 'resendMail'),
('MSITE', 'updateContent'),
('MNEWS', 'updateNews'),
('MSITE', 'updateSite'),
('MGALLERY', 'createGallery'),
('MGALLERY', 'deleteGallery'),
('MGALLERY', 'editGallery'),
('MGALLERY', 'updateGallery'),
('MSITE', 'addSiteContent'),
('MSITE', 'deleteSiteContent'),
('MSITE', 'updateContentText');
