language: php

php:
  - 5.4

addons:
  sauce_connect:
    username: "mrbirne"
    access_key: "930becfc-4cda-4152-a309-3fa01a078814"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - composer install
  - export PATH=../../vendor/bin:$PATH
  - mkdir ./assets
  - mkdir ./protected/runtime
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS cmstest DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
  - mysql -u root -e "CREATE USER 'cms'@'localhost' IDENTIFIED BY 'BCv4r2hrfhw4ahrc'"
  - mysql -u root -e "GRANT USAGE ON * . * TO 'cms'@'localhost' IDENTIFIED BY 'BCv4r2hrfhw4ahrc' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON cmstest . * TO 'cms'@'localhost';"
  - mysql -u root cmstest < ./DB.sql
  - mysql -u root cmstest < ./sql/rights/create.sql

script:
  - cd ./protected/tests
  - phpunit --coverage-clover ../../clover.xml -c phpunit-travis.xml ./functional/LoginTest.php

after_script:
  - cd ../..
  - php vendor/bin/coveralls -v
