language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  - ./travis_scripts/create_mysql.sh
  - ./travis_scripts/create_dir.sh

script:
  - php ./vendor/bin/phpunit ./protected/tests/unit
