language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install
  - mkdir ./assets
  - mkdir ./protected/runtime
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS 'cmstest' DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
  - mysql -uroot -e "CREATE USER 'cms'@'localhost' IDENTIFIED BY 'BCv4r2hrfhw4ahrc';"
  - mysql -uroot -e "GRANT USAGE ON * . * TO 'cms'@'localhost' IDENTIFIED BY 'BCv4r2hrfhw4ahrc' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON 'cmstest' . * TO 'cms'@'localhost';"
  - mysql -uroot cmstest < ./DB.sql
  - mysql -uroot cmstest < ./sql/rights/create.sql

script:
  - php ./vendor/bin/phpunit ./protected/tests/unit
